In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','score','placed'])

In [3]:
df.head()

cgpa  score  placed
0     8      8       1
1     7      9       1
2     6     10       0
3     5      5       0

In [6]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [8]:
model=Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.get_weights()

[array([[-0.7027576 ,  0.21974981],
        [ 0.22329068, -0.99626887]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.4133786 ],
        [0.40908575]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
opt=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=opt)

In [15]:
model.fit(df.iloc[:,:-1].values,df['placed'].values,epochs=60,verbose=1,batch_size=1)

Epoch 1/60
4/4 [==============================] - 0s 6ms/step - loss: 0.6985
Epoch 2/60
4/4 [==============================] - 0s 5ms/step - loss: 0.6985
Epoch 3/60
4/4 [==============================] - 0s 6ms/step - loss: 0.6984
Epoch 4/60
4/4 [==============================] - 0s 5ms/step - loss: 0.6983
Epoch 5/60
4/4 [==============================] - 0s 5ms/step - loss: 0.6982
Epoch 6/60
4/4 [==============================] - 0s 6ms/step - loss: 0.6981
Epoch 7/60
4/4 [==============================] - 0s 5ms/step - loss: 0.6980
Epoch 8/60
4/4 [==============================] - 0s 5ms/step - loss: 0.6980
Epoch 9/60
4/4 [==============================] - 0s 5ms/step - loss: 0.6979
Epoch 10/60
4/4 [==============================] - 0s 6ms/step - loss: 0.6978
Epoch 11/60
4/4 [==============================] - 0s 4ms/step - loss: 0.6977
Epoch 12/60
4/4 [==============================] - 0s 6ms/step - loss: 0.6976
Epoch 13/60
4/4 [==============================] - 0s 6ms/step - loss: 0.